### PR TITLE
nor2 cell completed

### PR DESCRIPTION
**Pull request by sdlims**
Completed nor2_1, nor2_2, nor2_4, and nor2_8. All L, W, and transistor counts are consistent with the efabless library. Resolved width issue by correctly placing transistors in parallel (not series)

### CODE REVIEW

**Comment by sdlims** [comment]
I understand everything except the fingers comment. Say for nor2_8, would you want all the transistors on the same level then? One line of transistors, with A's and B's grouped together?

**Comment by sifferman** [comment]
Whatever you feel looks the best. I just want all fingers to be next to each other, and in the same orientation in the schematic.

**Comment by sdlims** [comment]
I just pushed the changes you asked for, I made schematics cleaner and optimized placement of transistors

**Comment by sifferman** [comment]
Thanks for all your help! Please observe the final changes that I made to improve the readability: <https://github.com/sifferman/sky130_schematics/releases/latest>

**Comment by sdlims** [comment]
I see the changes now. I assumed you would want transistors of the same configuration paired together (SD vs DS). I'll keep this formatting in mind for future cells

**Comment by sifferman** [comment]
Oh, I see. Yeah, that's not really important.

**Pull request merged**
