### PR TITLE
Completed nor2b cells

### PR DESCRIPTION
**Pull request by sdlims**
Re-forked repo and uploaded completed nor2b cells

### CODE REVIEW

**Comment by sifferman** [comment]
Nice! You're quick!

Can you make them a bit more pretty. There are labels that are too close, and overlapping wires. For nor2b, I recommend making a disjoint B_N -> inverter -> B section, similar to the dff schematic. Any inverters should very clearly look like inverters. And nor gates should clearly look like nor gates. They shouldn't overlap

And the larger cells should be organized similar to how I showed you for the nor2 cells. All related fingers should be grouped together

Also, please pull from main again. I just added another check which your schematics are failing

**Comment by sdlims** [comment]
Sorry I didn't see the notification that you commented on this PR. I'll get on this and it should be updated quickly

**Comment by sdlims** [comment]
Known issue: The svg is messed up for the i/o, I'm completely unsure what's causing this issue despite attempted fixes

**Comment by sifferman** [comment]
Weird, I have never seen a seg fault there. I am not sure what the issue is

Although, note that the order of the ports matter. You should open the .sch files in a text editor, and move the "ipin"s and "opin"s to appear in the order specified by the sky130 spice file.

**Comment by sdlims** [comment]
I can do that, I'll get on it soon!

**Comment by sdlims** [comment]
Ok so I sort of messed things up and unintentionally made the changes on a branch. I'm going to close this PR and open a new PR that will include the updated .sch files and nor3b files

**Pull request closed without merging**
